import {
  AdminOrder,
  AdminProduct,
  AdminCategory,
  AdminDeliveryZone,
  AdminCoupon,
  DashboardKPIs,
} from '../types/admin';

export const INITIAL_KPIS: DashboardKPIs = {
  totalRevenueNpr: 184500,
  revenueGrowthPercent: 18.4,
  totalOrdersToday: 342,
  ordersGrowthPercent: 22.1,
  activeDeliveriesCount: 28,
  averageDeliveryMinutes: 9.4,
  platformSplit: {
    mobileAppOrders: 254, // ~74% Mobile
    mobileAppRevenue: 138600,
    webOrders: 88, // ~26% Web
    webRevenue: 45900,
  },
  lowStockItemsCount: 4,
};

export const INITIAL_CATEGORIES: AdminCategory[] = [
  {
    id: 'alcohol',
    name: 'Hard Drinks & Liquors (Alcohol)',
    slug: 'alcohol',
    tagline: 'Whisky, wine, beer & spirits',
    image: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=500',
    icon: 'Wine',
    color: '#7C3AED',
    productCount: 28,
    isActive: true,
    displayOrder: 1,
    subcategories: [
      'Whisky',
      'Beer',
      'Gorkha',
      'Gorkha Strong',
      'Gorkha Premium',
      'Nepal Ice',
      'Nepal Ice Strong',
      'Arna',
      'Arna 8',
      'Barahsinghe',
      'Barahsinghe Craft',
      'Tuborg',
      'Carlsberg',
      'Budweiser',
      'San Miguel',
      'Corona',
      'Wine',
      'Vodka',
      'Rum',
      'Tequila',
      'Gin',
      'Golden Oak',
      'Black Oak',
      'Mustang Gold',
      'Highlander',
      'Blue Diamond',
      'Blue Oak',
      'Silver Oak',
      'Kala Patthar',
      'Aristocrat Classic',
      'Baron Select',
      'Royal Blue',
      'Virgin Black',
      "McDowell's No.1",
      'Emperor',
      'Bio Whisky',
      'Old Durbar',
      'Old Durbar Black Chimney',
      'Old Durbar 12 Years',
      'Old Durbar 15 Years',
      'Signature Rare Aged',
      'Signature Premium',
      'Gurkhas & Guns',
      'J89',
      'Yarchagumba Golden Sapphire',
    ],
  },
  {
    id: 'cigarettes',
    name: 'Cigarettes & Tobacco',
    slug: 'cigarettes',
    tagline: 'Familiar brands, delivered',
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=500',
    icon: 'Flame',
    color: '#4B5563',
    productCount: 4,
    isActive: true,
    displayOrder: 2,
    subcategories: ['Cigarettes', 'Lighters', 'Smoking Accessories'],
  },
  {
    id: 'snacks',
    name: 'Snacks & Munchies',
    slug: 'snacks',
    tagline: 'Chips, nuts & quick bites',
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500',
    icon: 'Cookie',
    color: '#B93B3B',
    productCount: 5,
    isActive: true,
    displayOrder: 3,
    subcategories: ['Chips', 'Nuts', 'Chocolates', 'Quick Bites', 'Noodles'],
  },
  {
    id: 'cold-drinks',
    name: 'Drinks & Mixers (Cold Drinks)',
    slug: 'cold-drinks',
    tagline: 'Soft drinks, water & mixers',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500',
    icon: 'Coffee',
    color: '#0F766E',
    productCount: 6,
    isActive: true,
    displayOrder: 4,
    subcategories: ['Soft Drinks', 'Energy Drinks', 'Fruit Juice', 'Water', 'Mixers'],
  },
];

export const INITIAL_PRODUCTS: AdminProduct[] = [
  // ==========================================
  // ALCOHOL BRANDS
  // ==========================================
  {
    id: 'b-go-1',
    name: 'Golden Oak Reserve Blended Whisky',
    slug: 'golden-oak-whisky',
    category: 'Hard Drinks & Liquors (Alcohol)',
    categoryId: 'alcohol',
    unit: '750 ml',
    price: 1450,
    mrp: 1600,
    stockQuantity: 40,
    isAvailable: true,
    isFlashDeal: true,
    isDealOfTheDay: true,
    isPopularNow: true,
    isHardDrinks: true,
    showOnMobileApp: true,
    showOnWeb: true,
    thumbnailUrl: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=300',
    updatedAt: 'Today, 10:15 AM',
  },
  {
    id: 'b-bo-1',
    name: 'Black Oak Rare Reserve Grain Whisky',
    slug: 'black-oak-whisky',
    category: 'Hard Drinks & Liquors (Alcohol)',
    categoryId: 'alcohol',
    unit: '750 ml',
    price: 1550,
    mrp: 1700,
    stockQuantity: 35,
    isAvailable: true,
    isFlashDeal: false,
    isDealOfTheDay: false,
    isPopularNow: true,
    isHardDrinks: true,
    showOnMobileApp: true,
    showOnWeb: true,
    thumbnailUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=300',
    updatedAt: 'Today, 10:15 AM',
  },
  {
    id: 'b-mg-1',
    name: 'Mustang Gold Rare Nepali Whisky',
    slug: 'mustang-gold-whisky',
    category: 'Hard Drinks & Liquors (Alcohol)',
    categoryId: 'alcohol',
    unit: '750 ml',
    price: 1650,
    mrp: 1800,
    stockQuantity: 30,
    isAvailable: true,
    isFlashDeal: false,
    isDealOfTheDay: false,
    isPopularNow: false,
    isHardDrinks: true,
    showOnMobileApp: true,
    showOnWeb: true,
    thumbnailUrl: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=300',
    updatedAt: 'Today, 10:15 AM',
  },
  {
    id: 'b-kp-1',
    name: 'Kala Patthar Himalayan Peated Whisky',
    slug: 'kala-patthar-whisky',
    category: 'Hard Drinks & Liquors (Alcohol)',
    categoryId: 'alcohol',
    unit: '750 ml',
    price: 2850,
    mrp: 3200,
    stockQuantity: 25,
    isAvailable: true,
    isFlashDeal: true,
    isDealOfTheDay: true,
    isPopularNow: true,
    isHardDrinks: true,
    showOnMobileApp: true,
    showOnWeb: true,
    thumbnailUrl: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=300',
    updatedAt: 'Today, 11:30 AM',
  },
  {
    id: 'w-od-1',
    name: 'Old Durbar Black Chimney Craft Whisky',
    slug: 'old-durbar-black-chimney',
    category: 'Hard Drinks & Liquors (Alcohol)',
    categoryId: 'alcohol',
    unit: '750 ml',
    price: 3600,
    mrp: 3950,
    stockQuantity: 24,
    isAvailable: true,
    isFlashDeal: true,
    isDealOfTheDay: true,
    isPopularNow: true,
    isHardDrinks: true,
    showOnMobileApp: true,
    showOnWeb: true,
    thumbnailUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=300',
    updatedAt: 'Today, 11:45 AM',
  },
  {
    id: 'b-od-12',
    name: 'Old Durbar 12 Years Aged Malt Whisky',
    slug: 'old-durbar-12-years',
    category: 'Hard Drinks & Liquors (Alcohol)',
    categoryId: 'alcohol',
    unit: '750 ml',
    price: 5400,
    mrp: 5900,
    stockQuantity: 5,
    isAvailable: true,
    isFlashDeal: false,
    isDealOfTheDay: false,
    isPopularNow: true,
    isHardDrinks: true,
    showOnMobileApp: true,
    showOnWeb: true,
    thumbnailUrl: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=300',
    updatedAt: 'Today, 12:00 PM',
  },
  {
    id: 'b-od-15',
    name: 'Old Durbar 15 Years Reserve Single Cask',
    slug: 'old-durbar-15-years',
    category: 'Hard Drinks & Liquors (Alcohol)',
    categoryId: 'alcohol',
    unit: '750 ml',
    price: 7800,
    mrp: 8500,
    stockQuantity: 0,
    isAvailable: false,
    isFlashDeal: false,
    isDealOfTheDay: false,
    isPopularNow: true,
    isHardDrinks: true,
    showOnMobileApp: true,
    showOnWeb: true,
    thumbnailUrl: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=300',
    updatedAt: 'Today, 12:00 PM',
  },
  {
    id: 'b-sig-rare',
    name: 'Signature Rare Aged Grain Whisky',
    slug: 'signature-rare-aged',
    category: 'Hard Drinks & Liquors (Alcohol)',
    categoryId: 'alcohol',
    unit: '750 ml',
    price: 2750,
    mrp: 3000,
    stockQuantity: 35,
    isAvailable: true,
    isFlashDeal: false,
    isDealOfTheDay: false,
    isPopularNow: true,
    isHardDrinks: true,
    showOnMobileApp: true,
    showOnWeb: true,
    thumbnailUrl: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=300',
    updatedAt: 'Today, 09:15 AM',
  },
  {
    id: 'b-sig-prem',
    name: 'Signature Premier Aged Indian Whisky',
    slug: 'signature-premium',
    category: 'Hard Drinks & Liquors (Alcohol)',
    categoryId: 'alcohol',
    unit: '750 ml',
    price: 2950,
    mrp: 3200,
    stockQuantity: 28,
    isAvailable: true,
    isFlashDeal: false,
    isDealOfTheDay: false,
    isPopularNow: true,
    isHardDrinks: true,
    showOnMobileApp: true,
    showOnWeb: true,
    thumbnailUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=300',
    updatedAt: 'Today, 09:15 AM',
  },
  {
    id: 'b-gguns-1',
    name: 'Gurkhas & Guns Two Tigers Fine Blend',
    slug: 'gurkhas-and-guns-whisky',
    category: 'Hard Drinks & Liquors (Alcohol)',
    categoryId: 'alcohol',
    unit: '750 ml',
    price: 3800,
    mrp: 4200,
    stockQuantity: 22,
    isAvailable: true,
    isFlashDeal: true,
    isDealOfTheDay: true,
    isPopularNow: true,
    isHardDrinks: true,
    showOnMobileApp: true,
    showOnWeb: true,
    thumbnailUrl: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=300',
    updatedAt: 'Today, 10:30 AM',
  },
  {
    id: 'b-yarcha-1',
    name: 'Yarchagumba Golden Sapphire Elixir Whisky',
    slug: 'yarchagumba-golden-sapphire',
    category: 'Hard Drinks & Liquors (Alcohol)',
    categoryId: 'alcohol',
    unit: '750 ml',
    price: 12500,
    mrp: 14000,
    stockQuantity: 3,
    isAvailable: true,
    isFlashDeal: true,
    isDealOfTheDay: false,
    isPopularNow: true,
    isHardDrinks: true,
    showOnMobileApp: true,
    showOnWeb: true,
    thumbnailUrl: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=300',
    updatedAt: 'Today, 10:30 AM',
  },
  {
    id: 'p4',
    name: 'Tuborg Classic Premium Strong Beer (650ml)',
    slug: 'tuborg-beer',
    category: 'Hard Drinks & Liquors (Alcohol)',
    categoryId: 'alcohol',
    unit: '650 ml Bottle',
    price: 380,
    mrp: 420,
    stockQuantity: 60,
    isAvailable: true,
    isFlashDeal: false,
    isDealOfTheDay: false,
    isPopularNow: true,
    isHardDrinks: true,
    showOnMobileApp: true,
    showOnWeb: true,
    thumbnailUrl: 'https://images.unsplash.com/photo-1618886614638-80e3c15cd819?w=300',
    updatedAt: 'Yesterday',
  },

  // ==========================================
  // CIGARETTES
  // ==========================================
  {
    id: 'p12',
    name: 'Marlboro Red King Size (Pack of 20)',
    slug: 'marlboro-red',
    category: 'Cigarettes & Tobacco',
    categoryId: 'cigarettes',
    unit: 'Pack of 20',
    price: 660,
    mrp: 700,
    stockQuantity: 50,
    isAvailable: true,
    isFlashDeal: false,
    isDealOfTheDay: false,
    isPopularNow: true,
    isCigarettes: true,
    showOnMobileApp: true,
    showOnWeb: true,
    thumbnailUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=300',
    updatedAt: 'Today, 08:45 AM',
  },
  {
    id: 'p13',
    name: 'Surya 24 Carat Lights (Pack of 20)',
    slug: 'surya-lights',
    category: 'Cigarettes & Tobacco',
    categoryId: 'cigarettes',
    unit: 'Pack of 20',
    price: 450,
    mrp: 480,
    stockQuantity: 45,
    isAvailable: true,
    isFlashDeal: false,
    isDealOfTheDay: false,
    isPopularNow: true,
    isCigarettes: true,
    showOnMobileApp: true,
    showOnWeb: true,
    thumbnailUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=300',
    updatedAt: 'Today, 08:45 AM',
  },

  // ==========================================
  // SNACKS
  // ==========================================
  {
    id: 'p15',
    name: 'Lay’s Classic Salted Potato Chips (115g)',
    slug: 'classic-potato-chips',
    category: 'Snacks & Munchies',
    categoryId: 'snacks',
    unit: '115 g Pouch',
    price: 150,
    mrp: 170,
    stockQuantity: 70,
    isAvailable: true,
    isFlashDeal: false,
    isDealOfTheDay: false,
    isPopularNow: true,
    isSnacks: true,
    showOnMobileApp: true,
    showOnWeb: true,
    thumbnailUrl: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=300',
    updatedAt: 'Today, 08:45 AM',
  },

  // ==========================================
  // COLD DRINKS
  // ==========================================
  {
    id: 'p20',
    name: 'Red Bull Energy Drink (4 Cans Pack)',
    slug: 'red-bull-energy-drink',
    category: 'Drinks & Mixers (Cold Drinks)',
    categoryId: 'cold-drinks',
    unit: '4 x 250 ml Cans',
    price: 720,
    mrp: 800,
    stockQuantity: 65,
    isAvailable: true,
    isFlashDeal: true,
    isDealOfTheDay: true,
    isPopularNow: true,
    isDrinksAndMixers: true,
    showOnMobileApp: true,
    showOnWeb: true,
    thumbnailUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=300',
    updatedAt: 'Today, 10:00 AM',
  },
];

export const INITIAL_ORDERS: AdminOrder[] = [
  {
    id: 'ord-1',
    orderNumber: 'MOJ-94821',
    customerName: 'Jay Prakash Yadav',
    customerPhone: '9841234567',
    platform: 'MobileApp',
    items: [
      {
        id: 'oi-1',
        productId: 'b-go-1',
        productName: 'Golden Oak Reserve Blended Whisky',
        unit: '750 ml',
        quantity: 2,
        unitPrice: 1450,
        totalPrice: 2900,
      },
    ],
    itemCount: 2,
    subtotal: 2900,
    deliveryFee: 100,
    discount: 0,
    totalAmount: 3000,
    paymentMethod: 'eSewa',
    paymentStatus: 'Completed',
    orderStatus: 'OutForDelivery',
    deliveryAddress: {
      street: 'House #14, Jhamsikhel Road',
      area: 'Jhamsikhel',
      city: 'Lalitpur',
    },
    estimatedDeliveryEtaMinutes: 12,
    createdAt: '8 mins ago',
  },
  {
    id: 'ord-2',
    orderNumber: 'MOJ-94822',
    customerName: 'Aayush Maharjan',
    customerPhone: '9818765432',
    platform: 'Web',
    items: [
      {
        id: 'oi-2',
        productId: 'w-od-1',
        productName: 'Old Durbar Black Chimney Craft Whisky',
        unit: '750 ml',
        quantity: 1,
        unitPrice: 3600,
        totalPrice: 3600,
      },
    ],
    itemCount: 1,
    subtotal: 3600,
    deliveryFee: 100,
    discount: 200,
    totalAmount: 3500,
    paymentMethod: 'Khalti',
    paymentStatus: 'Completed',
    orderStatus: 'Preparing',
    deliveryAddress: {
      street: 'Sanepa Heights, Ward 2',
      area: 'Sanepa',
      city: 'Lalitpur',
    },
    estimatedDeliveryEtaMinutes: 15,
    createdAt: '14 mins ago',
  },
  {
    id: 'ord-3',
    orderNumber: 'MOJ-94823',
    customerName: 'Sunita Thapa',
    customerPhone: '9849988776',
    platform: 'MobileApp',
    items: [
      {
        id: 'oi-3',
        productId: 'b-kp-1',
        productName: 'Kala Patthar Himalayan Peated Whisky',
        unit: '750 ml',
        quantity: 1,
        unitPrice: 2850,
        totalPrice: 2850,
      },
    ],
    itemCount: 1,
    subtotal: 2850,
    deliveryFee: 100,
    discount: 0,
    totalAmount: 2950,
    paymentMethod: 'COD',
    paymentStatus: 'Pending',
    orderStatus: 'Confirmed',
    deliveryAddress: {
      street: 'Baluwatar Prime, Gate 2',
      area: 'Baluwatar',
      city: 'Kathmandu',
    },
    estimatedDeliveryEtaMinutes: 20,
    createdAt: '22 mins ago',
  },
];

export const INITIAL_DELIVERY_ZONES: AdminDeliveryZone[] = [
  {
    id: 'zone-1',
    name: 'Kathmandu Core (Thamel, Naxal, Baluwatar)',
    city: 'Kathmandu',
    darkStoreHub: 'Hub-02 (Baluwatar)',
    standardEtaMinutes: 14,
    expressEtaMinutes: 10,
    isActive: true,
    isSurgePricing: false,
    activeRidersCount: 9,
    pendingOrdersCount: 2,
  },
  {
    id: 'zone-2',
    name: 'Lalitpur Express (Jhamsikhel, Sanepa, Pulchowk)',
    city: 'Lalitpur',
    darkStoreHub: 'Hub-01 (Jhamsikhel)',
    standardEtaMinutes: 12,
    expressEtaMinutes: 8,
    isActive: true,
    isSurgePricing: true,
    activeRidersCount: 12,
    pendingOrdersCount: 4,
  },
  {
    id: 'zone-3',
    name: 'Baneshwor & Koteshwor (East Kathmandu)',
    city: 'Kathmandu',
    darkStoreHub: 'Hub-03 (Baneshwor)',
    standardEtaMinutes: 15,
    expressEtaMinutes: 12,
    isActive: true,
    isSurgePricing: false,
    activeRidersCount: 7,
    pendingOrdersCount: 1,
  },
];

export const INITIAL_ZONES = INITIAL_DELIVERY_ZONES;

export const INITIAL_COUPONS: AdminCoupon[] = [
  {
    id: 'c-1',
    code: 'APPFIRST',
    discountType: 'fixed',
    discountValue: 200,
    minOrderAmount: 1500,
    validFor: 'MobileApp',
    usageCount: 312,
    isActive: true,
    expiresAt: '2026-12-31',
  },
  {
    id: 'c-2',
    code: 'MIDNIGHT50',
    discountType: 'fixed',
    discountValue: 50,
    minOrderAmount: 800,
    validFor: 'All',
    usageCount: 589,
    isActive: true,
    expiresAt: '2026-12-31',
  },
];
